version: "3.3"

services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: root
      POSTGRES_DB: exams
    ports:
      - "5432:5432"

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  # Optionally, add other services like a web app, etc.
  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db

volumes:
  postgres_data:
    driver: local
